"""Pluggable OCR engines used by the local image-text adapter.

The production path is intentionally dependency-light: operators can inject any
callable OCR engine, use the optional Tesseract CLI wrapper when available, or
run the built-in PBM glyph demo to prove that image pixels can flow through the
same adapter without downloading a model.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Iterable


class OCRRuntimeError(RuntimeError):
    """Raised when a configured OCR engine cannot extract text."""


class TesseractCliOCREngine:
    """OCR engine backed by an installed ``tesseract`` binary."""

    def __init__(self, *, executable: str = "tesseract", language: str = "chi_sim+eng", timeout_seconds: float = 10.0) -> None:
        self.executable = executable
        self.language = language
        self.timeout_seconds = timeout_seconds

    def __call__(self, image_path: str | Path) -> str:
        binary = shutil.which(self.executable)
        if not binary:
            raise OCRRuntimeError(f"tesseract_not_found:{self.executable}")
        result = subprocess.run(  # noqa: S603 - explicit executable and local image path only.
            [binary, str(image_path), "stdout", "-l", self.language],
            check=False,
            capture_output=True,
            text=True,
            timeout=self.timeout_seconds,
        )
        if result.returncode != 0:
            raise OCRRuntimeError(f"tesseract_failed:{result.stderr.strip() or result.returncode}")
        return result.stdout.strip()


class BitmapGlyphOCREngine:
    """No-dependency OCR demo for PBM glyph images generated by this module.

    It is deliberately small, but it is still a real OCR path: the engine reads
    PBM image pixels, segments glyph columns, and maps glyph bitmaps to text.
    This keeps the demo reproducible on Windows without adding Pillow,
    pytesseract, or model downloads.
    """

    default_ocr_confidence = 1.0

    def __init__(self, *, unknown_char: str = "?") -> None:
        self.unknown_char = unknown_char
        self._reverse_font = {_glyph_key(_trim_glyph(value)): key for key, value in DEMO_FONT.items()}

    def __call__(self, image_path: str | Path) -> str:
        width, height, pixels = read_pbm_pixels(image_path)
        if height != FONT_HEIGHT:
            raise OCRRuntimeError(f"unsupported_demo_font_height:{height}")
        glyphs = _split_glyphs(width, height, pixels)
        return "".join(self._reverse_font.get(_glyph_key(_trim_glyph(glyph)), self.unknown_char) for glyph in glyphs)


def render_demo_pbm(text: str, output_path: str | Path) -> Path:
    """Render demo text into a PBM image accepted by ``BitmapGlyphOCREngine``."""

    normalized = text.upper()
    glyph_rows: list[list[int]] = [[] for _ in range(FONT_HEIGHT)]
    for char_index, char in enumerate(normalized):
        glyph = DEMO_FONT.get(char)
        if glyph is None:
            if char == " ":
                glyph = ["0" for _ in range(FONT_HEIGHT)]
            else:
                raise ValueError(f"unsupported demo OCR glyph: {char!r}")
        if char_index:
            for row in glyph_rows:
                row.append(0)
        for row_index, row_bits in enumerate(glyph):
            glyph_rows[row_index].extend(1 if bit == "1" else 0 for bit in row_bits)
    width = len(glyph_rows[0]) if glyph_rows else 0
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = ["P1", "# BlackAgent demo OCR PBM", f"{width} {FONT_HEIGHT}"]
    lines.extend(" ".join(str(bit) for bit in row) for row in glyph_rows)
    output.write_text("\n".join(lines) + "\n", encoding="ascii")
    return output


def read_pbm_pixels(path: str | Path) -> tuple[int, int, list[list[int]]]:
    tokens = list(_pbm_tokens(Path(path).read_text(encoding="ascii")))
    if not tokens or tokens[0] != "P1":
        raise OCRRuntimeError("unsupported_pbm_format:expected_P1")
    if len(tokens) < 3:
        raise OCRRuntimeError("invalid_pbm_header")
    width = int(tokens[1])
    height = int(tokens[2])
    raw_bits = [int(value) for value in tokens[3:]]
    if len(raw_bits) != width * height:
        raise OCRRuntimeError(f"invalid_pbm_size:{len(raw_bits)}!={width * height}")
    return width, height, [raw_bits[index * width : (index + 1) * width] for index in range(height)]


def _pbm_tokens(text: str) -> Iterable[str]:
    for line in text.splitlines():
        line = line.split("#", 1)[0]
        for token in line.split():
            yield token


def _split_glyphs(width: int, height: int, pixels: list[list[int]]) -> list[list[str]]:
    glyphs: list[list[str]] = []
    start: int | None = None
    for column in range(width + 1):
        blank = column == width or all(pixels[row][column] == 0 for row in range(height))
        if blank:
            if start is not None:
                glyphs.append([
                    "".join("1" if pixels[row][col] else "0" for col in range(start, column))
                    for row in range(height)
                ])
                start = None
            continue
        if start is None:
            start = column
    return glyphs


def _glyph_key(glyph: Iterable[str]) -> tuple[str, ...]:
    return tuple(str(row) for row in glyph)


def _trim_glyph(glyph: Iterable[str]) -> list[str]:
    rows = [str(row) for row in glyph]
    if not rows:
        return []
    width = max(len(row) for row in rows)
    padded = [row.ljust(width, "0") for row in rows]
    non_blank_cols = [
        index
        for index in range(width)
        if any(row[index] == "1" for row in padded)
    ]
    if not non_blank_cols:
        return ["0" for _ in rows]
    start = non_blank_cols[0]
    end = non_blank_cols[-1] + 1
    return [row[start:end] for row in padded]


FONT_HEIGHT = 7

DEMO_FONT: dict[str, list[str]] = {
    "0": ["11111", "10001", "10011", "10101", "11001", "10001", "11111"],
    "1": ["00100", "01100", "00100", "00100", "00100", "00100", "01110"],
    "2": ["11110", "00001", "00001", "11110", "10000", "10000", "11111"],
    "3": ["11110", "00001", "00001", "01110", "00001", "00001", "11110"],
    "4": ["10010", "10010", "10010", "11111", "00010", "00010", "00010"],
    "5": ["11111", "10000", "10000", "11110", "00001", "00001", "11110"],
    "6": ["01111", "10000", "10000", "11110", "10001", "10001", "01110"],
    "7": ["11111", "00001", "00010", "00100", "01000", "01000", "01000"],
    "8": ["01110", "10001", "10001", "01110", "10001", "10001", "01110"],
    "9": ["01110", "10001", "10001", "01111", "00001", "00001", "11110"],
    ":": ["00000", "00100", "00100", "00000", "00100", "00100", "00000"],
    "A": ["01110", "10001", "10001", "11111", "10001", "10001", "10001"],
    "C": ["01111", "10000", "10000", "10000", "10000", "10000", "01111"],
    "G": ["01111", "10000", "10000", "10011", "10001", "10001", "01111"],
    "O": ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
    "R": ["11110", "10001", "10001", "11110", "10100", "10010", "10001"],
    "T": ["11111", "00100", "00100", "00100", "00100", "00100", "00100"],
}


__all__ = [
    "BitmapGlyphOCREngine",
    "OCRRuntimeError",
    "TesseractCliOCREngine",
    "read_pbm_pixels",
    "render_demo_pbm",
]
