source_name_prefix: telegram_public_delivery
channels:
- channel: haoshangmashang
  max_pages: 20
- channel: haoshango00
  max_pages: 10
- channel: alanghome
  max_pages: 20
- channel: tgzs88
  max_pages: 20
- channel: huzige1916
  max_pages: 15
- channel: quannenghao
  max_pages: 5
- channel: tgchqf
  max_pages: 5
- channel: tgliuxing
  max_pages: 5
- channel: Dragon_Userbot
  max_pages: 15
- channel: thunderuserbot
  max_pages: 8
- channel: moonuserbot
  max_pages: 15
- channel: rkg_automation
  max_pages: 5
- channel: haizhuma
  max_pages: 5
- channel: yeziyui
  max_pages: 5
- channel: amy531com
  max_pages: 3
- channel: jiema010101
  max_pages: 3
- channel: AccountOps_Lab
  max_pages: 15
- channel: aidedzhou5
  max_pages: 10
- channel: chuanghuikeji02
  max_pages: 10
- channel: jymhpd
  max_pages: 5
- channel: xthaoorg
  max_pages: 15
- channel: chaojiyun88
  max_pages: 5
- channel: hao_dfyJm
  max_pages: 5
- channel: inoprjiema
  max_pages: 10
- channel: jiemaD2
  max_pages: 10
- channel: sifangsms
  max_pages: 5
- channel: szfangsims1
  max_pages: 5
- channel: thesupersms
  max_pages: 10
- channel: tiger_sms_china
  max_pages: 10
- channel: xiaoji1212
  max_pages: 5
- channel: yeziyun1122
  max_pages: 5
- channel: yutumma
  max_pages: 5
- channel: ymdajpd
  max_pages: 10
- channel: z6252
  max_pages: 10
- channel: paopaopayment
  max_pages: 5
- channel: zh_cnmhzh
  max_pages: 5
- channel: xieyihao89
  max_pages: 8
- channel: SMSzhb001
  max_pages: 5
- channel: bamlp
  max_pages: 8
- channel: dongdongtgyinliu
  max_pages: 8
- channel: jiema_0001
  max_pages: 5
- channel: jiema_c0
  max_pages: 5
- channel: jifeng_TG
  max_pages: 5
- channel: ws6777
  max_pages: 5
- channel: TGchengpin
  max_pages: 12
- channel: haodi00
  max_pages: 12
- channel: heimayunkong1
  max_pages: 12
- channel: tme_iMX
  max_pages: 12
- channel: pidanruanjian
  max_pages: 12
- channel: kuajing003
  max_pages: 12
- channel: sms52011
  max_pages: 12
- channel: xiaodaji0
  max_pages: 12
- channel: LYZDH
  max_pages: 12
- channel: herosms_cn
  max_pages: 12
- channel: tgheji66
  max_pages: 20
- channel: didipifa
  max_pages: 12
- channel: feijisu
  max_pages: 12
- channel: laren_a2
  max_pages: 12
- channel: TGtelegram101
  max_pages: 20
- channel: momokejicc
  max_pages: 12
- channel: wsyk88
  max_pages: 12
- channel: HHweb_yk
  max_pages: 12
- channel: Shenjian999
  max_pages: 12
- channel: huojianyunkong5
  max_pages: 12
- channel: tgpermiumeb
  max_pages: 12
- channel: maotool
  max_pages: 12
- channel: tgcaihongjc
  max_pages: 12
- channel: bot_zh
  max_pages: 12
- channel: sggkkbot
  max_pages: 12
- channel: Automationforum
  max_pages: 125
