"""Collector exports under the product namespace."""

from src.collector import (
    DEFAULT_BLACKGRAY_INCLUDE_KEYWORDS,
    DEFAULT_DEFENSIVE_EXCLUDE_KEYWORDS,
    DEFAULT_FIXTURE_PATH,
    BaseCollector,
    HTTPFeedCollector,
    HTTPFeedConfig,
    KeywordRelevanceDecision,
    MockCollector,
    NetworkCollectionDisabled,
    SourceAuthorizationError,
    SourceCatalogError,
    build_raw_intelligence,
    decide_text_relevance,
    get_record_field,
    get_theme_search_terms,
    get_theme_search_variants,
    load_source_catalog,
    load_theme_synonym_registry,
    model_dump,
    normalize_keywords,
    normalize_themes,
)

__all__ = [
    "BaseCollector",
    "DEFAULT_BLACKGRAY_INCLUDE_KEYWORDS",
    "DEFAULT_DEFENSIVE_EXCLUDE_KEYWORDS",
    "DEFAULT_FIXTURE_PATH",
    "HTTPFeedCollector",
    "HTTPFeedConfig",
    "KeywordRelevanceDecision",
    "MockCollector",
    "NetworkCollectionDisabled",
    "SourceAuthorizationError",
    "SourceCatalogError",
    "build_raw_intelligence",
    "decide_text_relevance",
    "get_record_field",
    "get_theme_search_terms",
    "get_theme_search_variants",
    "load_source_catalog",
    "load_theme_synonym_registry",
    "model_dump",
    "normalize_keywords",
    "normalize_themes",
]
